### ISSUE TITLE
Please allow PHP 8

### ISSUE THREAD

**Issue by altraWeb** [beyondcode/laravel-query-detector#73]
Currently its fixed:

```yaml
"require": {
      "php": "^7.1",
      "illuminate/support": "^5.5 || ^6.0 || ^7.0 || ^8.0"
},
...
```

And this is why i can't fully upgrade to PHP 8 yet.

Thanks
